spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ollama_cache
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

ollama:
  api:
    url: http://localhost:11434

server:
  port: 8080
